// AUTO-GENERATED by src/codegen/fromHar.ts — do not edit by hand.
// Regenerate: bun run codegen <har>
import type { Command } from "./types.ts";

export const commands: Command[] = [
  {
    "name": [
      "api",
      "user",
      "github",
      "orgs",
      "create"
    ],
    "method": "POST",
    "path": "/api/user/github/orgs",
    "pathParams": [],
    "query": [],
    "bodyContentType": "application/json",
    "description": "POST /api/user/github/orgs"
  },
  {
    "name": [
      "assistant",
      "sessions"
    ],
    "method": "GET",
    "path": "/api/assistant/sessions",
    "pathParams": [],
    "query": [
      "status",
      "ownership",
      "limit",
      "installation_id"
    ],
    "description": "GET /api/assistant/sessions"
  },
  {
    "name": [
      "assistant",
      "sessions",
      "get"
    ],
    "method": "GET",
    "path": "/api/assistant/sessions/:session_id",
    "pathParams": [
      "session_id"
    ],
    "query": [],
    "description": "GET /api/assistant/sessions/:session_id"
  },
  {
    "name": [
      "branch-protection"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/branch-protection",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/branch-protection"
  },
  {
    "name": [
      "broadcasting",
      "auth",
      "create"
    ],
    "method": "POST",
    "path": "/broadcasting/auth",
    "pathParams": [],
    "query": [],
    "bodyContentType": "application/x-www-form-urlencoded",
    "description": "POST /broadcasting/auth"
  },
  {
    "name": [
      "codesmith-settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/codesmith-settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/codesmith-settings"
  },
  {
    "name": [
      "codesmith-settings",
      "mcp-providers"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/codesmith-settings/mcp-providers",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/codesmith-settings/mcp-providers"
  },
  {
    "name": [
      "codesmith-settings",
      "mcp-servers"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/codesmith-settings/mcp-servers",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/codesmith-settings/mcp-servers"
  },
  {
    "name": [
      "codesmith-settings",
      "skills"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/codesmith-settings/skills",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/codesmith-settings/skills"
  },
  {
    "name": [
      "docker-container-caching"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/docker-container-caching",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/docker-container-caching"
  },
  {
    "name": [
      "email-alert-threshold"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/email-alert-threshold",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/email-alert-threshold"
  },
  {
    "name": [
      "github-comments"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/github-comments",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/github-comments"
  },
  {
    "name": [
      "has-onboarded"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/has-onboarded",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/has-onboarded"
  },
  {
    "name": [
      "has-payment-method"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/has-payment-method",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/has-payment-method"
  },
  {
    "name": [
      "is-personal-org"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/is-personal-org",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/is-personal-org"
  },
  {
    "name": [
      "linear",
      "install-url"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/linear/install-url",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/linear/install-url"
  },
  {
    "name": [
      "linear",
      "link"
    ],
    "method": "GET",
    "path": "/api/user/linear/link",
    "pathParams": [],
    "query": [],
    "description": "GET /api/user/linear/link"
  },
  {
    "name": [
      "linear",
      "workspace"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/linear/workspace",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/linear/workspace"
  },
  {
    "name": [
      "log-ingestion",
      "settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/log-ingestion/settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/log-ingestion/settings"
  },
  {
    "name": [
      "max-timeout",
      "settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/max-timeout/settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/max-timeout/settings"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "branches"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/branches",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "repository"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/branches"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "daily"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/daily",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "repositories[]"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/daily"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "job-duration-histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/job-duration-histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "bucket_count",
      "repositories[]"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/job-duration-histogram"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "job-duration-histogram",
      "exemplars"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/job-duration-histogram/exemplars",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "percentiles[]",
      "repositories[]"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/job-duration-histogram/exemplars"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "jobs"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/jobs",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "repository"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/jobs"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "repositories"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/repositories",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/repositories"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "runner-types"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/runner-types",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "repositories[]"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/runner-types"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "runs"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/runs",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "limit"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/runs"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "runs",
      "filter-options"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/runs/filter-options",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/runs/filter-options"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "runs",
      "histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/runs/histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "bucket_count"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/runs/histogram"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "split-graph"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/split-graph",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "sort_method",
      "metric",
      "dimension",
      "top_n",
      "repository"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/split-graph"
  },
  {
    "name": [
      "metrics",
      "actions",
      "jobs",
      "standalone"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/jobs/standalone",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "repositories[]"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/jobs/standalone"
  },
  {
    "name": [
      "metrics",
      "actions",
      "workflows",
      "runs"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/workflows/runs",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "limit"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/workflows/runs"
  },
  {
    "name": [
      "metrics",
      "actions",
      "workflows",
      "runs",
      "filter-options"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/workflows/runs/filter-options",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/workflows/runs/filter-options"
  },
  {
    "name": [
      "metrics",
      "actions",
      "workflows",
      "runs",
      "histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/workflows/runs/histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "bucket_count"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/workflows/runs/histogram"
  },
  {
    "name": [
      "metrics",
      "actions",
      "workflows",
      "runs",
      "jobs",
      "get"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/actions/workflows/runs/:run_id/jobs/:job_id",
    "pathParams": [
      "org",
      "run_id",
      "job_id"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/metrics/actions/workflows/runs/:run_id/jobs/:job_id"
  },
  {
    "name": [
      "metrics",
      "core-usage",
      "current"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/core-usage/current",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/metrics/core-usage/current"
  },
  {
    "name": [
      "metrics",
      "core-usage",
      "timeseries"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/core-usage/timeseries",
    "pathParams": [
      "org"
    ],
    "query": [
      "window_size",
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/core-usage/timeseries"
  },
  {
    "name": [
      "metrics",
      "daily"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/daily",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/daily"
  },
  {
    "name": [
      "metrics",
      "docker",
      "build-duration-histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/build-duration-histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "bucket_count"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/build-duration-histogram"
  },
  {
    "name": [
      "metrics",
      "docker",
      "daily"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/daily",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/daily"
  },
  {
    "name": [
      "metrics",
      "docker",
      "daily-by-type"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/daily-by-type",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/daily-by-type"
  },
  {
    "name": [
      "metrics",
      "docker",
      "repositories"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/repositories",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/repositories"
  },
  {
    "name": [
      "metrics",
      "docker",
      "split-graph"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/split-graph",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date",
      "metric",
      "dimension",
      "top_n"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/split-graph"
  },
  {
    "name": [
      "metrics",
      "docker",
      "standalone"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/standalone",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/standalone"
  },
  {
    "name": [
      "metrics",
      "docker",
      "sticky-disk",
      "total"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/docker/sticky-disk/total",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/docker/sticky-disk/total"
  },
  {
    "name": [
      "metrics",
      "invoice-amount"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/invoice-amount",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/metrics/invoice-amount"
  },
  {
    "name": [
      "metrics",
      "logs",
      "histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/logs/histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "query",
      "start_time",
      "end_time"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/logs/histogram"
  },
  {
    "name": [
      "metrics",
      "logs",
      "search"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/logs/search",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_time",
      "end_time",
      "query"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/logs/search"
  },
  {
    "name": [
      "metrics",
      "logs",
      "search",
      "filter-options"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/logs/search/filter-options",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_time",
      "end_time",
      "property"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/logs/search/filter-options"
  },
  {
    "name": [
      "metrics",
      "repositories"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/repositories",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/repositories"
  },
  {
    "name": [
      "metrics",
      "runner-types"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/runner-types",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/runner-types"
  },
  {
    "name": [
      "metrics",
      "stickydisks"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/stickydisks",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/stickydisks"
  },
  {
    "name": [
      "metrics",
      "stickydisks",
      "repositories",
      "get"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/stickydisks/repositories/:repo",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/stickydisks/repositories/:repo"
  },
  {
    "name": [
      "metrics",
      "stickydisks",
      "repositories",
      "summary"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/stickydisks/repositories/:repo/summary",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/stickydisks/repositories/:repo/summary"
  },
  {
    "name": [
      "metrics",
      "total"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/metrics/total",
    "pathParams": [
      "org"
    ],
    "query": [
      "start_date",
      "end_date"
    ],
    "description": "GET /api/user/github/orgs/:org/metrics/total"
  },
  {
    "name": [
      "migrate-runners",
      "repositories"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/migrate-runners/repositories",
    "pathParams": [
      "org"
    ],
    "query": [
      "search",
      "per_page"
    ],
    "description": "GET /api/user/github/orgs/:org/migrate-runners/repositories"
  },
  {
    "name": [
      "monitoring",
      "failure-histogram"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/failure-histogram",
    "pathParams": [
      "org"
    ],
    "query": [
      "repository",
      "workflow",
      "job",
      "step_name",
      "step_results[]"
    ],
    "description": "GET /api/user/github/orgs/:org/monitoring/failure-histogram"
  },
  {
    "name": [
      "monitoring",
      "repositories"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/repositories",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/monitoring/repositories"
  },
  {
    "name": [
      "monitoring",
      "repositories",
      "branches"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/repositories/:repo/branches",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/monitoring/repositories/:repo/branches"
  },
  {
    "name": [
      "monitoring",
      "repositories",
      "jobs"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/repositories/:repo/jobs",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [
      "workflow"
    ],
    "description": "GET /api/user/github/orgs/:org/monitoring/repositories/:repo/jobs"
  },
  {
    "name": [
      "monitoring",
      "repositories",
      "steps"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/repositories/:repo/steps",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [
      "workflow",
      "job"
    ],
    "description": "GET /api/user/github/orgs/:org/monitoring/repositories/:repo/steps"
  },
  {
    "name": [
      "monitoring",
      "repositories",
      "workflows"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/repositories/:repo/workflows",
    "pathParams": [
      "org",
      "repo"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/monitoring/repositories/:repo/workflows"
  },
  {
    "name": [
      "monitoring",
      "rules"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/monitoring/rules",
    "pathParams": [
      "org"
    ],
    "query": [
      "timeline_start_date",
      "timeline_end_date",
      "limit"
    ],
    "description": "GET /api/user/github/orgs/:org/monitoring/rules"
  },
  {
    "name": [
      "primary-email"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/primary-email",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/primary-email"
  },
  {
    "name": [
      "runner-region"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/runner-region",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/runner-region"
  },
  {
    "name": [
      "slack",
      "install-url"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/slack/install-url",
    "pathParams": [
      "org"
    ],
    "query": [
      "source"
    ],
    "description": "GET /api/user/github/orgs/:org/slack/install-url"
  },
  {
    "name": [
      "slack",
      "link"
    ],
    "method": "GET",
    "path": "/api/user/slack/link",
    "pathParams": [],
    "query": [],
    "description": "GET /api/user/slack/link"
  },
  {
    "name": [
      "slack",
      "workspace"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/slack/workspace",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/slack/workspace"
  },
  {
    "name": [
      "ssh",
      "settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/ssh/settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/ssh/settings"
  },
  {
    "name": [
      "team"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/team",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/team"
  },
  {
    "name": [
      "unpaid-invoices"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/unpaid-invoices",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/unpaid-invoices"
  },
  {
    "name": [
      "user-autofix-settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/user-autofix-settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/user-autofix-settings"
  },
  {
    "name": [
      "user-pr-comment-settings"
    ],
    "method": "GET",
    "path": "/api/user/github/orgs/:org/user-pr-comment-settings",
    "pathParams": [
      "org"
    ],
    "query": [],
    "description": "GET /api/user/github/orgs/:org/user-pr-comment-settings"
  }
];
